Basic architecture done
williambulin/epitech_game_engine pull request #31
Opened 2020-10-12 16:21 UTC by aFranchon

Adding AudioListener => nothing in it, it will be used for 3D Audio

Adding AudioManager => For creation and managment of AudioSources and AudioGroups

Adding AudioGroup struct => To change settings in all linked AudioSources

Adding AudioSource => The main class to play sounds

2020-10-28 01:58 UTC, williambulin requested changes

2020-10-28 09:30 UTC, aFranchon commented on source/Audio/AudioManager.cpp
> +    m_Instance = new AudioManager;
I thought what i did was already a singleton pattern implementation (I think than only one global audio manager would be easier to use) why should singletons be avoided ?

2020-10-29 12:52 UTC, williambulin requested changes

2020-10-29 12:52 UTC, williambulin commented on source/Audio/AudioManager.cpp
> +    m_Instance = new AudioManager;
Generally, when you implement a singleton pattern, you keep the instance of the object inside it's function itself
```cpp
[[nodiscard]] auto getSingleton() -> MyObject & {
  static MyObject myObject{}; // or a ptr, depends on your resource type and how you intend to access it 
  return myObject;
}
```

They should be avoided because you should avoid designing objects that can only be created once. In these cases, namespaces are preferred to classes.

2020-10-31 14:19 UTC, aFranchon commented on source/Audio/AudioManager.cpp
> +    m_Instance = new AudioManager;
Ok singleton has been removed everything is updated, push coming soon

2020-11-09 23:10 UTC, merged